// <auto-generated />
namespace SafariBooks_Employee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MK));
        
        string IMigrationMetadata.Id
        {
            get { return "201511260243440_MK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
